# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scotblood Levels
description: > # this means to ignore newlines until "baseurl:"
    A graph of Scotblood's stock levels
github_username:  SCOTPAUL
baseurl: /scotblood-levels
# Build settings
markdown: kramdown

gems:
    - jekyll-assets
    - uglifier

assets:
  compress:
    css: true
    js: true
  cache: false
  prefix: "/assets"
  assets:
    - "*.js"
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - "_assets/js"
